# Generated by Django 4.2.7 on 2023-11-06 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(choices=[(0, 'Завод'), (1, 'Дистрибьютор'), (2, 'Дилерский центр'), (3, 'Крупная розничная сеть'), (4, 'Индивидуальный предприниматель')], help_text='Выберите уровень иерархии')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ('created_at',), 'verbose_name': 'Торговая сеть', 'verbose_name_plural': 'Торговые сети'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='network',
        ),
        migrations.RemoveField(
            model_name='network',
            name='level',
        ),
        migrations.AddField(
            model_name='network',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.employee'),
        ),
        migrations.RemoveField(
            model_name='network',
            name='product',
        ),
        migrations.AddField(
            model_name='network',
            name='product',
            field=models.ManyToManyField(related_name='network_products', to='ecommerceapp.product'),
        ),
        migrations.AlterField(
            model_name='network',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerceapp.supplier'),
        ),
    ]
