# Generated by Django 4.2.7 on 2025-05-08 14:49

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='network',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name='employees',
                to='ecommerceapp.network',
            ),
        ),
    ]