# Generated by Django 4.2.7 on 2025-05-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0002_add_network_to_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="ecommerceapp.network",
                verbose_name="Торговая сеть",
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="level",
            field=models.IntegerField(
                choices=[
                    (0, "Завод"),
                    (1, "Дистрибьютор"),
                    (2, "Дилерский центр"),
                    (3, "Крупная розничная сеть"),
                    (4, "Индивидуальный предприниматель"),
                ],
                default=0,
                help_text="Выберите уровень иерархии",
                verbose_name="Уровень иерархии",
            ),
        ),
    ]
