# Generated by Django 4.2.7 on 2023-11-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_alter_product_name_alter_supplier_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='level',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Дистрибьютор'), (2, 'Дилерский центр'), (3, 'Крупная розничная сеть'), (4, 'Индивидуальный предприниматель')], default=0, help_text='Выберите уровень иерархии'),
        ),
    ]
